#!/bin/bash/

if [ ${UID} -ne 0 ]
then
echo
echo "You need root access"
echo
exit 1
fi
## Check number of processors

if [ nproc -eq 1 ]
then echo "this server is very small"
	exit 2
fi
# Checking memory
free -m



exit 0
 bd61278da364ebe13a053d4c12f504bf7a1f1f9e
